[tox]
skipsdist = True
envlist =
    py312-{module,flake8,lizard,mypy,ruff}
    flake8
    mypy
    ruff
skip_missing_interpreters = True

[testenv:py312-module]
deps = -rrequirements-test.txt
commands =
    python3 -m pytest --cov-config=pyproject.toml --cov=. --cov-report=html --cov-report=xml --cov-report=term-missing tests

[testenv:py312-flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules

[testenv:py312-lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules -C 15

[testenv:py312-mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules

[testenv:py312-ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules
